# Generated by Django 5.0.1 on 2024-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
